steps:
  - name: ':rspec: RSpec'
    command: test.sh
    timeout_in_minutes: 10
    plugins:
      - ssh://git@github.com/Gusto/cloudsmith-auth-buildkite-plugin.git#v2.2.0: ~
      - docker-compose#v5.6.0:
          run: app
          config: .buildkite/docker-compose.yml
          env:
            - BUNDLE_DL__CLOUDSMITH__IO
            - CLOUDSMITH_API_KEY
  - name: ':sorbet: Sorbet typecheck'
    command: typecheck.sh
    timeout_in_minutes: 10
    plugins:
      - ssh://git@github.com/Gusto/cloudsmith-auth-buildkite-plugin.git#v2.2.0: ~
      - docker-compose#v5.6.0:
          run: app
          config: .buildkite/docker-compose.yml
          env:
            - BUNDLE_DL__CLOUDSMITH__IO
            - CLOUDSMITH_API_KEY
  - wait
  - block: ':rocket: Publish to Gem Server?'
    branches: main
  - name: ':ruby: Publish to Rubygems'
    branches: main
    agents:
      queue: gemstash-publish
    command: gem build explicit_activerecord.gemspec && .buildkite/store_rubygems_key.sh && gem push --key rubygems *.gem
